# Crear el archivo nixpacks.toml
@"
[phases.setup]
nixPkgs = ["nodejs_18", "yarn"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn start"
"@ | Out-File -FilePath "nixpacks.toml" -Encoding UTF8